# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

resources:
 containers:
   - container: redis
     image: redis
     ports: 
     - 6379

pool:
  vmImage: 'ubuntu-latest'

services:
  redis: redis

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    sudo apt install -y redis-tools
    redis-cli -h redis ping
  displayName: Test redis connection

- task: Npm@1
  inputs:
    command: install
  displayName: npm install before test

- task: Npm@1
  inputs:
    command: custom
    customCommand: run test
  displayName: Running tests
  continueOnError: true

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
    mergeTestResults: true
    testRunTitle: 'All tests results'
  displayName: Publish tests results

- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/cobertura-coverage.xml'
  displayName: Publish code coverage

- script: |
    npm install
    cd $(Build.Repository.LocalPath)/src/hermes_modules/composition/
    npm install
    cd $(Build.Repository.LocalPath)
    npm run compileCompositionPackage
  displayName: 'npm install and compile Composition package'

- script: |
    $(Build.Repository.LocalPath)/src/hermes_modules/topic/
    npm install
    cd $(Build.Repository.LocalPath)
    npm run compileTopicPackage
  displayName: 'npm install and compile Topic Package'

- task: Npm@1
  displayName: 'Publish Composition to azuredevops Hermes/hermes feed'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), eq(variables['publishComposition'],'true'))
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: Hermes/hermes
    workingDir: $(Build.Repository.LocalPath)/src/hermes_modules/composition/

- task: Npm@1
  displayName: 'Publish topic to azuredevops Hermes/hermes feed'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), eq(variables['publishTopic'],'true'))
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: Hermes/hermes
    workingDir: $(Build.Repository.LocalPath)/src/hermes_modules/topic/


