# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    cd $(Build.Repository.LocalPath)/src/services/composition/
    npm install
    cd $(Build.Repository.LocalPath)
    npm run buildCompositionPackage
  displayName: 'npm install and build Composition package'

- script: |
    $(Build.Repository.LocalPath)/src/services/topic/
    npm install
    cd $(Build.Repository.LocalPath)
    npm run buildTopicPackage
  displayName: 'npm install and build Topic Package'

- task: Npm@1
  inputs:
    command: custom
    customCommand: run test
  displayName: Running tests
  continueOnError: true

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
    mergeTestResults: true
    testRunTitle: 'All tests results'
  displayName: Publish tests results

- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/cobertura.xml'
  displayName: Publish code coverage

- task: Npm@1
  displayName: 'Publish Composition to azuredevops Hermes/hermes feed'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), eq(variables['publishComposition'],'true'))
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: Hermes/hermes
    workingDir: $(Build.Repository.LocalPath)/src/services/composition/

- task: Npm@1
  displayName: 'Publish topic to azuredevops Hermes/hermes feed'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), eq(variables['publishTopic'],'true'))
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: Hermes/hermes
    workingDir: $(Build.Repository.LocalPath)/src/services/topic/


