# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    cd $(Build.Repository.LocalPath)/src/services/composition/
    npm install
    cd $(Build.Repository.LocalPath)
    npm run buildCompositionPackage
  displayName: 'npm install and build Composition package'

- task: Npm@1
  displayName: 'Publish Composition to azuredevops Hermes/hermes feed'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), variables['publishComposition'])
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: Hermes/hermes
    workingDir: $(Build.Repository.LocalPath)/src/services/composition/

- script: |
    $(Build.Repository.LocalPath)/src/services/topic/
    npm install
    cd $(Build.Repository.LocalPath)
    npm run buildTopicPackage
  displayName: 'npm install and build Topic Package'

- task: Npm@1
  displayName: 'Publish topic to azuredevops Hermes/hermes feed'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), variables['publishCTopic'])
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: Hermes/hermes
    workingDir: $(Build.Repository.LocalPath)/src/services/topic/

    
